apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nameko-api
  name: nameko-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nameko-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nameko-api
    spec:
      containers:
        - image: 10.10.0.1:5000/nameko-api:v1
          name: nameko-api
          imagePullPolicy: "IfNotPresent"
          env:
            - name: REDIS_HOST
              value: redis-svc.default.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
            - name: RABBIT_HOST
              value: rmq-svc.default.svc.cluster.local
            - name: RABBIT_USER
              value: guest
            - name: RABBIT_PASSWORD
              value: guest
            - name: RABBIT_PORT
              value: "5672"
          resources: {}
status: {}
